{% set name = "shogun-cpp" %}
{% set version = "6.1.0" %}
{% set build = 0 %}
{% set commit = "9c36e70a49d25da4bc91c90664d4c93e046ce519" %} # XXX tmp
{% set sha256 = "4a2e63bca499828706201419ea4843c4bdc8c2a952197b58e5b2afc14f4c6e10" %}

# Shogun doesn't produce a single tarball you can build from anymore;
# need to get the gpl-shogun tarball too. Remember to update this when updating
# the version!
{% set gpl_commit = "29ca2ff930cd5d963b3a78e79160cc04d48970c2" %}
{% set gpl_sha256 = "ff8a46b7775e784f07e9ffb02e7cd9b101f508c1c7b7d8cdbf1024a2efacdb22" %}

{% set blas_variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: shogun_{{ version }}.tar.gz
  # url: https://github.com/shogun-toolbox/shogun/archive/shogun_{{ version }}.tar.gz
  url: https://github.com/shogun-toolbox/shogun/archive/{{ commit }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  features:
    - blas_{{ blas_variant }}
  skip:
    - True  # [win]
  script:
    - set -ex  # not automatically done by conda-build 2

    # HACK: download the gpl tarball
    - curl https://github.com/shogun-toolbox/shogun-gpl/archive/{{ gpl_commit }}.tar.gz -O shogun-gpl.tar.gz
    - [[ $(openssl sha256 shogun-gpl.tar.gz | cut -d' ' -f2) == "{{ gpl_sha256 }}" ]]
    - tar xf shogun-gpl.tar.gz

    - mkdir build
    - cd build
    - |
        cmake .. \
          -DCMAKE_PREFIX_PATH="$PREFIX" \
          -DCMAKE_INSTALL_PREFIX="$PREFIX" \
          -DCMAKE_BUILD_TYPE=Release \
          -DBUILD_EXAMPLES=OFF \
          -DBUILD_META_EXAMPLES=OFF \
          -DBUNDLE_JSON=OFF \
          -DBUNDLE_NLOPT=OFF \
          -DUSE_SVMLIGHT=OFF \
          -DENABLE_TESTING=OFF \
          -DENABLE_COVERAGE=OFF \
          -DLICENSE_GPL_SHOGUN=ON
    - make -j $CPU_COUNT
    - make install -j $CPU_COUNT

requirements:
  build:
    - toolchain
    - arpack 3.5.*
    - bzip2 1.0.*
    - cmake
    - ctags
    - curl >=7.44.0,<8
    - eigen
    - glpk 4.61|4.62
    - hdf5 1.10.1
    - json-c 0.12|0.12.*
    - libxml2 2.9.*
    - lzo 2.*
    - openblas 0.2.20|0.2.20.*
    - openssl  # not linked against
    - protobuf 3.4.*
    - snappy 1.1.6|1.1.7
    - xz 5.2.*
    - zlib 1.2.11
  run:
    - arpack 3.5.*
    - bzip2 1.0.*
    - ctags
    - curl >=7.44.0,<8
    - glpk 4.61|4.62
    - hdf5 1.10.1
    - json-c 0.12|0.12.*
    - libxml2 2.9.*
    - lzo 2.*
    - openblas 0.2.20|0.2.20.*
    - protobuf 3.4.*
    - snappy 1.1.6|1.1.7
    - xz 5.2.*
    - zlib 1.2.11

test:
  requires:
    - python
  commands:
    - python -c "import ctypes; ctypes.cdll['${PREFIX}/lib/libshogun${SHLIB_EXT}']"  # [unix]
    - $PREFIX/share/shogun/examples/libshogun/minimal-example  # [unix]

about:
  home: http://shogun.ml
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'Unified and efficient Machine Learning'
  description: |
    The Shogun Machine learning toolbox offers a wide range of efficient and
    unified Machine Learning methods.
  doc_url: http://shogun.ml/examples/latest/index.html
  dev_url: https://github.com/shogun-toolbox/shogun/wiki

extra:
  recipe-maintainers:
    - dougalsutherland
