{% set name = "shogun-cpp" %}
{% set version = "6.1.0" %}
{% set build = 0 %}
{% set sha256 = "39ab403b967876b4c6e4ad131fbb370a27e511bc775f822e27eb8514ae5b688b" %}
{% set blas_variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: shogun_{{ version }}.tar.gz
  # url: https://github.com/shogun-toolbox/shogun/archive/shogun_{{ version }}.tar.gz
  url: https://github.com/shogun-toolbox/shogun/archive/f0f95831b6a7ae3a924d12114c517d00fbb3da52.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  features:
    - blas_{{ blas_variant }}
  skip:
    - True  # [win]

requirements:
  build:
    - toolchain
    - arpack 3.5.*
    - bzip2 1.0.*
    - cmake
    - ctags
    - curl >=7.44.0,<8
    - eigen
    - glpk 4.61|4.62
    - hdf5 1.10.1
    - json-c 0.12|0.12.*
    - libxml2 2.9.*
    - lzo 2.*
    - openblas 0.2.20|0.2.20.*
    - protobuf 3.4.*
    - snappy 1.1.6|1.1.7
    - xz 5.2.*
    - zlib 1.2.11
  run:
    - arpack 3.5.*
    - bzip2 1.0.*
    - ctags
    - curl >=7.44.0,<8
    - glpk 4.61|4.62
    - hdf5 1.10.1
    - json-c 0.12|0.12.*
    - libxml2 2.9.*
    - lzo 2.*
    - openblas 0.2.20|0.2.20.*
    - protobuf 3.4.*
    - snappy 1.1.6|1.1.7
    - xz 5.2.*
    - zlib 1.2.11

test:
  requires:
    - python
  commands:
    - python -c "import ctypes; ctypes.cdll['${PREFIX}/lib/libshogun${SHLIB_EXT}']"  # [unix]
    - $PREFIX/share/shogun/examples/libshogun/minimal-example  # [unix]

about:
  home: http://shogun.ml
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'Unified and efficient Machine Learning'
  description: |
    The Shogun Machine learning toolbox offers a wide range of efficient and
    unified Machine Learning methods.
  doc_url: http://shogun.ml/examples/latest/index.html
  dev_url: https://github.com/shogun-toolbox/shogun/wiki

extra:
  recipe-maintainers:
    - dougalsutherland
