{% set name = "shogun-cpp" %}

{% set version = "6.1.2" %}
{% set commit = 'shogun_' + version %}
{% set sha256 = "50cd1482d9977933b6ab4e410f4debc00bfa935fdf2812e41edb73504757c0df" %}

# Shogun doesn't produce a single tarball you can build from anymore;
# need to get the gpl-shogun tarball too. Remember to update this when updating
# the version!
{% set gpl_commit = "29ca2ff930cd5d963b3a78e79160cc04d48970c2" %}
{% set gpl_sha256 = "ff8a46b7775e784f07e9ffb02e7cd9b101f508c1c7b7d8cdbf1024a2efacdb22" %}
{% set gpl_url = "http://github.com/shogun-toolbox/shogun-gpl/archive/" + gpl_commit + ".tar.gz" %}

{% set build = 2 %}

{% set blas_variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: shogun_{{ version }}.tar.gz
  url: https://github.com/shogun-toolbox/shogun/archive/{{ commit }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: {{ build }}
  features:
    - blas_{{ blas_variant }}  # [not win]
  skip:
    - true  # [win32]                     # shogun won't build 32-bit
    - true  # [win and py2k]              # shogun won't build on vc 9
    - true  # [win and py35]              # don't need to double up on vc14 builds
    - true  # [(not win) and (not py36)]  # don't do matrix builds on non-windows
  script:
    - set -ex  # not automatically done by conda-build 2  # [unix]

    # HACK: download the gpl tarball
    # When we migrate to conda-build 3, can have multiple sources:
    #  https://github.com/conda/conda-build/pull/1929
    - python $RECIPE_DIR/get_tarball.py  -c {{ gpl_sha256 }} -p src/gpl --strip-components 1 {{ gpl_url }}  # [unix]
    - python %RECIPE_DIR%/get_tarball.py -c {{ gpl_sha256 }} -p src/gpl --strip-components 1 {{ gpl_url }}  # [win]

    - mkdir build
    - cd build

    - |                                         # [unix]
        cmake .. \                              # [unix]
          -DCMAKE_PREFIX_PATH="$PREFIX" \       # [unix]
          -DCMAKE_INSTALL_PREFIX="$PREFIX" \    # [unix]
          -DCMAKE_BUILD_TYPE=Release \          # [unix]
          -DBUILD_EXAMPLES=OFF \                # [unix]
          -DBUILD_META_EXAMPLES=OFF \           # [unix]
          -DBUNDLE_JSON=OFF \                   # [unix]
          -DBUNDLE_NLOPT=OFF \                  # [unix]
          -DUSE_SVMLIGHT=OFF \                  # [unix]
          -DSWIG_EXECUTABLE=$PREFIX/bin/swig \  # [unix]
          -DENABLE_TESTING=OFF \                # [unix]
          -DENABLE_COVERAGE=OFF                 # [unix]
    - make -j $CPU_COUNT                        # [unix]
    - make install -j $CPU_COUNT                # [unix]

    - |                                                # [win]
        cmake .. ^                                     # [win]
          -G"%CMAKE_GENERATOR%" ^                      # [win]
          -DCMAKE_PREFIX_PATH="%LIBRARY_PREFIX%" ^     # [win]
          -DCMAKE_INSTALL_PREFIX="%LIBRARY_PREFIX%" ^  # [win]
          -DCMAKE_BUILD_TYPE=Release ^                 # [win]
          -DBUILD_EXAMPLES=OFF ^                       # [win]
          -DBUILD_META_EXAMPLES=OFF ^                  # [win]
          -DBUNDLE_JSON=OFF ^                          # [win]
          -DBUNDLE_NLOPT=OFF ^                         # [win]
          -DUSE_SVMLIGHT=OFF ^                         # [win]
          -DSWIG_EXECUTABLE=%LIBRARY_BIN%\\swig.exe ^  # [win]
          -DENABLE_TESTING=OFF ^                       # [win]
          -DENABLE_COVERAGE=OFF                        # [win]
    - if errorlevel 1 exit 1                           # [win]

    - msbuild /p:Configuration=Release src\\shogun\\libshogun.vcxproj      # [win]
    - if errorlevel 1 exit 1                                               # [win]

    - msbuild /p:Configuration=Release src\\shogun\\shogun.vcxproj         # [win]
    - if errorlevel 1 exit 1                                               # [win]

    - msbuild /p:Configuration=Release src\\shogun\\shogun-static.vcxproj  # [win]
    - if errorlevel 1 exit 1                                               # [win]

    - msbuild /p:Configuration=Release shogun.sln        # [win]
    - if errorlevel 1 exit 1                             # [win]

    - cmake --build . --target install --config Release  # [win]
    - if errorlevel 1 exit 1                             # [win]

requirements:
  build:
    - toolchain
    - python
    - requests  # used by get_tarball.py
    - vc 9    # [win and py27]
    - vc 10   # [win and py34]
    - vc 14   # [win and py>=35]
    - arpack 3.5.*              # [not win]
    - bzip2 1.0.*
    - cmake
    - ctags
    - curl >=7.44.0,<8
    - eigen                     # [not win]
    - eigen >=3.2,<3.3          # [win]
    - glpk 4.61|4.62
    - hdf5 1.10.1
    - json-c 0.12|0.12.*        # [not win]
    - libxml2 2.9.*
    - lzo 2.*
    - openblas 0.2.20|0.2.20.*  # [not win]
    - protobuf 3.4.*            # [not win] # conda-forge protobuf doesn't have C++ version
    - rxcpp 4.0.0
    - snappy 1.1.6|1.1.7
    - swig
    - xz 5.2.*
    - zlib 1.2.11
  run:
    - arpack 3.5.*              # [not win]
    - bzip2 1.0.*
    - ctags
    - curl >=7.44.0,<8
    - glpk 4.61|4.62
    - hdf5 1.10.1
    - json-c 0.12|0.12.*        # [not win]
    - libxml2 2.9.*
    - lzo 2.*
    - openblas 0.2.20|0.2.20.*  # [not win]
    - protobuf 3.4.*
    - snappy 1.1.6|1.1.7
    - xz 5.2.*
    - zlib 1.2.11

test:
  requires:
    - python
  commands:
    - $PREFIX/share/shogun/examples/libshogun/minimal                      # [unix]
    - '%LIBRARY_PREFIX%\\share\\shogun\\examples\\libshogun\\minimal.exe'  # [win]

    # check that one of the GPL headers was installed properly
    - test -f $PREFIX/include/shogun/mathematics/SparseInverseCovariance.h               # [unix]
    - if not exist %LIBRARY_INC%\\shogun\\mathematics\\SparseInverseCovariance.h exit 1  # [win]

    # linkage checks
    - python -c "import ctypes; ctypes.cdll['${PREFIX}/lib/libshogun${SHLIB_EXT}']"                      # [unix]
    - python -c "import os, ctypes; ctypes.cdll[os.path.join(os.environ['LIBRARY_LIB'], 'shogun.lib')]"  # [win]
    - conda inspect linkages -p $PREFIX {{ name }}  # [not win]
    - conda inspect objects  -p $PREFIX {{ name }}  # [osx]

about:
  home: http://shogun.ml
  license: GPL-3.0
  license_family: GPL
  license_file: COPYING
  summary: 'Unified and efficient Machine Learning'
  description: |
    The Shogun Machine learning toolbox offers a wide range of efficient and
    unified Machine Learning methods.
  doc_url: http://shogun.ml/examples/latest/index.html
  dev_url: https://github.com/shogun-toolbox/shogun/wiki

extra:
  recipe-maintainers:
    - dougalsutherland
