travis:
  secure:
    BINSTAR_TOKEN: TFR0LrKZl/yEcBkKWwfR7kbl3/7EZKiHXQrv3O63TsiZxjHZMMhYVsUcUMVrjN6SqGR4TteV5J/lcihTNm5/g0r2joFZa2zn82MZ8R/ySQZOGqQ3btZnUQ9V0kutHcxY3VfUg5IABMSRmlhqnbOeZa7f/vZ8lcPhk5EXAP1k0Bd6OxqhPsxu+hpSO91XukO/hiHbL8TBx7oL/XO/mqI+pglJQ4PwIvUav2qZmqXlDQLucu8MnF/ex3djbudgvQpMB6OHFv47MnuyKRviFU+UZlIkCBbHq17Ub7FPiwNZTrL3IXLdb+YuG81xkwlutVZj8focSregrmCVL895VTaRXfBWbJ4bW2HgqvgB+GCg4f7bepDVPa2R4XUTIYqMPEFrT7EIsobB0NiHpf/0r3rpbx9GbpqVo1FhcxfvoDgD4AP0jiV35dXiSYCxqHjBgTDCvQ88hhsK+Oj6a6O1OMP+N8qBWLG0QH1hd+blbsIrKN9m5aW4QCyfDu9rYMgYHUm5m2yjCWBetKsrnFo3uJsspMPe90/zJbxcAWDvTSuasZCEDYjodHTAcxdbq8EQkn1Ub3GdK9yVsl300iGT0GifYCYgN8j2QqVNMuIIs+vJHV5abGPM05B7xXjbIMnUTZbTNEqRhWdJ7Dq1OZsF7sz/TTEVTsXkuuiZnRvhzfQJXl8=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
