appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: B3sq+CCsXjtkyKHO3bPLnyBXX8qRZAS9qqK9skucMLodXnKBYVqOucvwcv1H9GkR43AMV1ZZLIIpxcgREVR2JZI3/ZWYsTmfkuKwFbCb18oeeBjTT8cx8NqKhnGeBSFslnMNmOnUvAWPXI1p5KrgAe67JBOQknDbi+T7tZPgJP1P9YHyTczA3nZXeFsJ9ZcCBEHCFnui7eL3mr259mSUzRLt3AV3gCqrFDTA5uyFLw5Ae1UzfUMuwbKZJ5BZ6G6MKp+G1qXzExIpelHaxqtZSju/CmSqKt53URsoE3FUkHlWpdbyyZKbfIdR6DPViJkJ4rgVcYd9gQaLqfsM8AVuFnsYeZuOBwyMT/FxPiJreYEgwSwqS2RcfZNdHIWUkg22YQmgv326tGoWL+yPApJd5k7JjpfFr6pCPBK3dGV5DQu/mTzvwX01QeI/F1t9s/QfLGg1tdPwFJDtIRySge63GN88vdixIQd2ptgSligvk1jbqQDdkHeOXQKt7ylM0S4jWET+TWOrZEKmyOklLE2bo/8/Egj8GrAFFXvcCHI5K3BCdMnJNwA4N40kvygVADFNeGc3xcDTNjsU0OmpeTWDhLVFISSRYn0Gp7jd8KD7Opk8KCWvcN/cayNjfKNSvQcBvRXI546+jdXiDRHCCtN0TyUrbkFTarTKXr8Oh79NoEw=}
provider:
  win: appveyor
